extends SceneTree

func _initialize() -> void:
	assert(Duelist.Weapon.KNIFE == 1)
	var m4_hip := Duelist.standing_speed_profile(Duelist.Weapon.PULSE, false)
	var m4_ads := Duelist.standing_speed_profile(Duelist.Weapon.PULSE, true)
	var knife := Duelist.standing_speed_profile(Duelist.Weapon.KNIFE, false)
	assert(is_equal_approx(float(m4_hip.forward), 7.2))
	assert(is_equal_approx(float(m4_hip.lateral), 5.472))
	assert(is_equal_approx(float(m4_ads.forward), 5.904))
	assert(is_equal_approx(float(m4_ads.lateral), 4.48704))
	assert(is_equal_approx(float(knife.forward), 8.28))
	assert(is_equal_approx(float(knife.lateral), 7.7004))
	assert(is_equal_approx(float(Duelist.mobility_facts(99 as Duelist.Weapon).get("hip_strafe", 0.0)), 0.76))
	assert(Duelist.first_person_kunai_position().y > -0.25)
	var kunai_rotation := Duelist.first_person_kunai_rotation()
	assert(kunai_rotation.x < -0.1)
	assert(kunai_rotation.z > 0.1)
	var eye := Vector3(1.0, 2.0, 3.0)
	var ads_origin := Duelist.shot_origin_for(eye, Basis.IDENTITY, true, Duelist.Weapon.PULSE)
	assert(ads_origin.distance_to(eye + Duelist.ads_iron_sight_tip_head_offset()) < 0.001)
	assert(ads_origin.distance_to(eye) > 0.01)
	print("Riftline weapon mobility exercise: PASS")
	quit()
